# this build works with container based envs
sudo: false

language: scala

# need to keep this in step with build.sbt
scala:
  - 2.11.7

# as of sept 2015 there is no "openjdk8"
jdk:
  - oraclejdk8

# script:
#   - sbt scoverage:test
#   - sbt coveralls

# after_success:
#   - sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish

# script: "sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport"

script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"

notifications:
  email:
    - brandon@bbrownsound.com

